export const CREATE_BLOG_COMMENT_SUCCESS = "CREATE_BLOG_COMMENT_SUCCESS";
export const CREATE_BLOG_COMMENT_REQUEST = "CREATE_BLOG_COMMENT_REQUEST";
export const CREATE_BLOG_COMMENT_FAILED = "CREATE_BLOG_COMMENT_FAILED";
export const CREATE_BLOG_COMMENT_RESET = "CREATE_BLOG_COMMENT_RESET";

export const GET_BLOG_COMMENT_SUCCESS = "GET_BLOG_COMMENT_SUCCESS";
export const GET_BLOG_COMMENT_REQUEST = "GET_BLOG_COMMENT_REQUEST";
export const GET_BLOG_COMMENT_FAILED = "GET_BLOG_COMMENT_FAILED";

export const COMMENT_CLEAR_ERROR="CATEGORY_CLEAR_ERROR";