export const BLOG_CATEGORY_SUCCESS="BLOG_CATEGORY_SUCCESS";
export const BLOG_CATEGORY_REQUEST="BLOG_CATEGORY_REQUEST";
export const BLOG_CATEGORY_FAILED="BLOG_CATEGORY_FAILED";


export const CREATE_CATEGORY_SUCCESS="CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_REQUEST="CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_FAILED="CREATE_CATEGORY_FAILED";
export const CREATE_CATEGORY_RESET="CREATE_CATEGORY_RESET";

export const DELETE_CATEGORY_SUCCESS="DELETE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY_REQUEST="DELETE_CATEGORY_REQUEST";
export const DELETE_CATEGORY_FAILED="DELETE_CATEGORY_FAILED";
export const DELETE_CATEGORY_RESET="DELETE_CATEGORY_RESET";

export const UPDATE_CATEGORY_SUCCESS="UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_REQUEST="UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_FAILED="UPDATE_CATEGORY_FAILED";
export const UPDATE_CATEGORY_RESET="UPDATE_CATEGORY_RESET";

export const CATEGORY_CLEAR_ERROR="CATEGORY_CLEAR_ERROR";