export const ADD_TO_CART_LOADING = 'ADD_TO_CART_LOADING';
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR';
export const ADD_TO_CART_CLEAR_ERROR = 'ADD_TO_CART_CLEAR_ERROR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';


export const SAVE_SHIPPING_LOADING = 'SAVE_SHIPPING_LOADING';
export const SAVE_SHIPPING_ITEM = 'SAVE_SHIPPING_ITEM';
export const SAVE_SHIPPING_ERROR = 'SAVE_SHIPPING_ERROR';