export const ALL_CATEGORIE_REQUEST = 'ALL_CATEGORIE_REQUEST';
export const ALL_CATEGORIE_SUCCESS = 'ALL_CATEGORIE_SUCCESS';
export const ALL_CATEGORIE_FAIL = 'ALL_CATEGORIE_FAIL';


export const NEW_CATEGORIE_REQUEST = 'NEW_CATEGORIE_REQUEST';
export const NEW_CATEGORIE_SUCCESS = 'NEW_CATEGORIE_SUCCESS';
export const NEW_CATEGORIE_FAIL = 'NEW_CATEGORIE_FAIL';
export const NEW_CATEGORIE_RESET = 'NEW_CATEGORIE_RESET';

export const STATUS_CATEGORIE_REQUEST = 'STATUS_CATEGORIE_REQUEST';
export const STATUS_CATEGORIE_SUCCESS = 'STATUS_CATEGORIE_SUCCESS';
export const STATUS_CATEGORIE_FAIL = 'STATUS_CATEGORIE_FAIL';
export const STATUS_CATEGORIE_RESET = 'STATUS_CATEGORIE_RESET';


export const STATUS_SUB_CATEGORIE_REQUEST = 'STATUS_SUB_CATEGORIE_REQUEST';
export const STATUS_SUB_CATEGORIE_SUCCESS = 'STATUS_SUB_CATEGORIE_SUCCESS';
export const STATUS_SUB_CATEGORIE_FAIL = 'STATUS_SUB_CATEGORIE_FAIL';
export const STATUS_SUB_CATEGORIE_RESET = 'STATUS_SUB_CATEGORIE_RESET';


export const GET_SINGLE_PRODUCT_CAT_REQUEST = 'GET_SINGLE_PRODUCT_CAT_REQUEST';
export const GET_SINGLE_PRODUCT_CAT_SUCCESS = 'GET_SINGLE_PRODUCT_CAT_SUCCESS';
export const GET_SINGLE_PRODUCT_CAT_FAIL = 'GET_SINGLE_PRODUCT_CAT_FAIL';


export const UPDATE_PARENT_CATEGORIE_REQUEST = 'UPDATE_PARENT_CATEGORIE_REQUEST';
export const UPDATE_PARENT_CATEGORIE_SUCCESS = 'UPDATE_PARENT_CATEGORIE_SUCCESS';
export const UPDATE_PARENT_CATEGORIE_FAIL = 'UPDATE_PARENT_CATEGORIE_FAIL';
export const UPDATE_PARENT_CATEGORIE_RESET = 'UPDATE_PARENT_CATEGORIE_RESET';


export const SINGLE_SUB_CATEGORIE_REQUEST = 'SINGLE_SUB_CATEGORIE_REQUEST';
export const SINGLE_SUB_CATEGORIE_SUCCESS = 'SINGLE_SUB_CATEGORIE_SUCCESS';
export const SINGLE_SUB_CATEGORIE_FAIL = 'SINGLE_SUB_CATEGORIE_FAIL';
export const SINGLE_SUB_CATEGORIE_RESET = 'SINGLE_SUB_CATEGORIE_RESET';

export const UPDATE_SUB_CATEGORIE_REQUEST = 'UPDATE_SUB_CATEGORIE_REQUEST';
export const UPDATE_SUB_CATEGORIE_SUCCESS = 'UPDATE_SUB_CATEGORIE_SUCCESS';
export const UPDATE_SUB_CATEGORIE_FAIL = 'UPDATE_SUB_CATEGORIE_FAIL';
export const UPDATE_SUB_CATEGORIE_RESET = 'UPDATE_SUB_CATEGORIE_RESET';


export const ALL_CATEGORIE_ERRORS = 'ALL_CATEGORIE_CLERA'; 