export const CREATE_CONTACT_SUCCESS="CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_REQUEST="CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_FAILED="CREATE_CONTACT_FAILED";
export const CREATE_CONTACT_RESET="CREATE_CONTACT_RESET";

export const GET_CONTACT_SUCCESS="GET_CONTACT_SUCCESS";
export const GET_CONTACT_REQUEST="GET_CONTACT_REQUEST";
export const GET_CONTACT_FAILED="GET_CONTACT_FAILED";

export const GET_SINGLE_CONTACT_SUCCESS="GET_SINGLE_CONTACT_SUCCESS";
export const GET_SINGLE_CONTACT_REQUEST="GET_SINGLE_CONTACT_REQUEST";
export const GET_SINGLE_CONTACT_FAILED="GET_SINGLE_CONTACT_FAILED";


export const Clear_Error="Clear_Error";