export const IMAGE_REQUEST = 'IMAGE_REQUEST';
export const IMAGE_SUCCESS = 'IMAGE_SUCCESS';
export const IMAGE_FAIL = 'IMAGE_FAIL';


export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST';
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS';
export const UPLOAD_IMAGE_FAIL = 'UPLOAD_IMAGE_FAIL';
export const UPLOAD_IMAGE_RESET = 'UPLOAD_IMAGE_RESET';

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST';
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS';
export const UPDATE_IMAGE_FAIL = 'UPDATE_IMAGE_FAIL';
export const UPDATE_IMAGE_RESET = 'UPDATE_IMAGE_RESET';


export const UPDATE_IMAGE_SEO_REQUEST = 'UPDATE_IMAGE_SEO_REQUEST';
export const UPDATE_IMAGE_SEO_SUCCESS = 'UPDATE_IMAGE_SEO_SUCCESS';
export const UPDATE_IMAGE_SEO_FAIL = 'UPDATE_IMAGE_SEO_FAIL';
export const UPDATE_IMAGE_SEO_RESET = 'UPDATE_IMAGE_SEO_RESET';

export const UPDATE_TEXT_REQUEST = 'UPDATE_TEXT_REQUEST';
export const UPDATE_TEXT_SUCCESS = 'UPDATE_TEXT_SUCCESS';
export const UPDATE_TEXT_FAIL = 'UPDATE_TEXT_FAIL';
export const UPDATE_TEXT_RESET = 'UPDATE_TEXT_RESET';


export const SET_SELECTED_IMAGE = 'SET_SELECTED_IMAGE';
export const SET_SELECTED_FAIL = 'SET_SELECTED_FAIL';
export const SET_SELECTED_IMAGE_RESET = 'SET_SELECTED_IMAGE_RESET';

export const IMAGE_ID_REQUEST = 'IMAGE_ID_REQUEST';
export const IMAGE_ID_SUCCESS = 'IMAGE_ID_SUCCESS';
export const IMAGE_ID_FAIL = 'IMAGE_ID_FAIL';
export const IMAGE_ID_RESET = 'IMAGE_ID_RESET';



export const IMAGE_CLEAR = 'IMAGE_CLEAR';