export const ALL_MASTER_COUPON_REQUEST = 'ALL_MASTER_COUPON_REQUEST'; 
export const ALL_MASTER_COUPON_SUCCESS = 'ALL_MASTER_COUPON_SUCCESS'; 
export const ALL_MASTER_COUPON_FAIL = 'ALL_MASTER_COUPON_FAIL'; 

export const CREATE_MASTER_COUPON_REQUEST = 'CREATE_MASTER_COUPON_REQUEST'; 
export const CREATE_MASTER_COUPON_SUCCESS = 'CREATE_MASTER_COUPON_SUCCESS'; 
export const CREATE_MASTER_COUPON_FAIL = 'CREATE_MASTER_COUPON_FAIL'; 
export const CREATE_MASTER_COUPON_RESET = 'CREATE_MASTER_COUPON_RESET'; 

export const VERIFY_MASTER_COUPON_REQUEST = 'VERIFY_MASTER_COUPON_REQUEST'; 
export const VERIFY_MASTER_COUPON_SUCCESS = 'VERIFY_MASTER_COUPON_SUCCESS'; 
export const VERIFY_MASTER_COUPON_FAIL = 'VERIFY_MASTER_COUPON_FAIL'; 
export const VERIFY_MASTER_COUPON_RESET = 'VERIFY_MASTER_COUPON_RESET'; 


export const ALL_MASTER_COUPON_CLEAR = 'ALL_MASTER_COUPON_CLEAR'; 