export const PAYMENT_INFO_FAIL = 'PAYMENT_INFO_FAIL';
export const PAYMENT_INFO_SUCCESS = 'PAYMENT_INFO_SUCCESS';
export const PAYMENT_INFO_REQUEST = 'PAYMENT_INFO_REQUEST';
export const PAYMENT_INFO_RESET = 'PAYMENT_INFO_REQUEST';


export const PAYMENT_DATA_FAIL = 'PAYMENT_DATA_FAIL';
export const PAYMENT_DATA_SUCCESS = 'PAYMENT_DATA_SUCCESS';
export const PAYMENT_DATA_REQUEST = 'PAYMENT_DATA_REQUEST';
export const PAYMENT_DATA_RESET = 'PAYMENT_DATA_REQUEST';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';