export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'; 
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'; 
export const ALL_PRODUCT_FAIL = 'ALL_PRODUCT_FAIL'; 
export const ALL_PRODUCT_RESET = 'ALL_PRODUCT_RESET'; 


export const PRODUCT_STATUS_REQUEST = 'PRODUCT_STATUS_REQUEST'; 
export const PRODUCT_STATUS_SUCCESS = 'PRODUCT_STATUS_SUCCESS'; 
export const PRODUCT_STATUS_FAIL = 'PRODUCT_STATUS_FAIL'; 
export const PRODUCT_STATUS_RESET = 'PRODUCT_STATUS_RESET'; 


export const ALL_PRODUCT_SEARCH_REQUEST = 'ALL_PRODUCT_SEARCH_REQUEST'; 
export const ALL_PRODUCT_SEARCH_SUCCESS = 'ALL_PRODUCT_SEARCH_SUCCESS'; 
export const ALL_PRODUCT_SEARCH_FAIL = 'ALL_PRODUCT_SEARCH_FAIL'; 
export const ALL_PRODUCT_SEARCH_RESET = 'ALL_PRODUCT_SEARCH_RESET'; 


export const ALL_FEATURE_PRODUCT_REQUEST = 'ALL_FEATURE_PRODUCT_REQUEST'; 
export const ALL_FEATURE_PRODUCT_SUCCESS = 'ALL_FEATURE_PRODUCT_SUCCESS'; 
export const ALL_FEATURE_PRODUCT_FAIL = 'ALL_FEATURE_PRODUCT_FAIL'; 


export const PRODUCCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'; 
export const PRODUCCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'; 
export const PRODUCCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'; 


export const ADMIN_PRODUCT_REQUEST = 'ADMIN_PRODUCT_REQUEST'; 
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS'; 
export const ADMIN_PRODUCT_FAIL = 'ADMIN_PRODUCT_FAIL';

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST';
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS';
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL';
export const NEW_PRODUCT_RESET = 'NEW_PRODUCT_RESET';


export const UPDATE_PRODUCT_REQUEST = 'UPDATE_PRODUCT_REQUEST';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL';
export const UPDATE_PRODUCT_RESET = 'UPDATE_PRODUCT_RESET';

export const DELETE_PRODUCT_REQUEST = 'DELETE_PRODUCT_REQUEST';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';
export const DELETE_PRODUCT_RESET = 'DELETE_PRODUCT_RESET';

export const ALL_CAT_REQUEST = 'ALL_CAT_REQUEST'; 
export const ALL_CAT_SUCCESS = 'ALL_CAT_SUCCESS'; 
export const ALL_CAT_FAIL = 'ALL_CAT_FAIL'; 

export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';


export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';


export const ALL_REVIEW_REQUEST = 'ALL_REVIEW_REQUEST';
export const ALL_REVIEW_SUCCESS = 'ALL_REVIEW_SUCCESS';
export const ALL_REVIEW_FAIL = 'ALL_REVIEW_FAIL';

//atrribute

export const CREATE_ATTRIBUTE_REQUEST = 'CREATE_ATTRIBUTE_REQUEST';
export const CREATE_ATTRIBUTE_SUCCESS = 'CREATE_ATTRIBUTE_SUCCESS';
export const CREATE_ATTRIBUTE_FAIL = 'CREATE_ATTRIBUTE_FAIL';
export const CREATE_ATTRIBUTE_RESET = 'CREATE_ATTRIBUTE_RESET';

export const DELETE_ATTRIBUTE_REQUEST = 'DELETE_ATTRIBUTE_REQUEST';
export const DELETE_ATTRIBUTE_SUCCESS = 'DELETE_ATTRIBUTE_SUCCESS';
export const DELETE_ATTRIBUTE_FAIL = 'DELETE_ATTRIBUTE_FAIL';
export const DELETE_ATTRIBUTE_RESET = 'DELETE_ATTRIBUTE_RESET'

export const GET_ATTRIBUTE_REQUEST = 'GET_ATTRIBUTE_REQUEST';
export const GET_ATTRIBUTE_SUCCESS = 'GET_ATTRIBUTE_SUCCESS';
export const GET_ATTRIBUTE_FAIL = 'GET_ATTRIBUTE_FAIL';
export const GET_ATTRIBUTE_RESET = 'GET_ATTRIBUTE_RESET';

export const GET_SINGLE_ATTRIBUTE_REQUEST = 'GET_SINGLE_ATTRIBUTE_REQUEST';
export const GET_SINGLE_ATTRIBUTE_SUCCESS = 'GET_SINGLE_ATTRIBUTE_SUCCESS';
export const GET_SINGLE_ATTRIBUTE_FAIL = 'GET_SINGLE_ATTRIBUTE_FAIL';
export const GET_SINGLE_ATTRIBUTE_RESET = 'GET_SINGLE_ATTRIBUTE_RESET';


export const UPDATE_ATTRIBUTE_REQUEST = 'UPDATE_ATTRIBUTE_REQUEST';
export const UPDATE_ATTRIBUTE_SUCCESS = 'UPDATE_ATTRIBUTE_SUCCESS';
export const UPDATE_ATTRIBUTE_FAIL = 'UPDATE_ATTRIBUTE_FAIL';
export const UPDATE_ATTRIBUTE_RESET = 'UPDATE_ATTRIBUTE_RESET';



//---------label------------------

export const CREATE_LABEL_REQUEST = 'CREATE_LABEL_REQUEST';
export const CREATE_LABEL_SUCCESS = 'CREATE_LABEL_SUCCESS';
export const CREATE_LABEL_FAIL = 'CREATE_LABEL_FAIL';
export const CREATE_LABEL_RESET = 'CREATE_LABEL_RESET';

export const GET_LABEL_REQUEST = 'GET_LABEL_REQUEST';
export const GET_LABEL_SUCCESS = 'GET_LABEL_SUCCESS';
export const GET_LABEL_FAIL = 'GET_LABEL_FAIL';

export const GET_ALL_LABEL_REQUEST = 'GET_ALL_LABEL_REQUEST';
export const GET_ALL_LABEL_SUCCESS = 'GET_ALL_LABEL_SUCCESS';
export const GET_ALL_LABEL_FAIL = 'GET_ALL_LABEL_FAIL';

export const GET_SINGLE_LABEL_REQUEST = 'GET_SINGLE_LABEL_REQUEST';
export const GET_SINGLE_LABEL_SUCCESS = 'GET_SINGLE_LABEL_SUCCESS';
export const GET_SINGLE_LABEL_FAIL = 'GET_SINGLE_LABEL_FAIL';

export const UPDATE_LABEL_REQUEST = 'UPDATE_LABEL_REQUEST'; 
export const UPDATE_LABEL_SUCCESS = 'UPDATE_LABEL_SUCCESS';
export const UPDATE_LABEL_FAIL = 'UPDATE_LABEL_FAIL';
export const UPDATE_LABEL_RESET = 'UPDATE_LABEL_RESET';

export const DELETE_LABEL_REQUEST = 'DELETE_LABEL_REQUEST'; 
export const DELETE_LABEL_SUCCESS = 'DELETE_LABEL_SUCCESS';
export const DELETE_LABEL_FAIL = 'DELETE_LABEL_FAIL';
export const DELETE_LABEL_RESET = 'DELETE_LABEL_RESET';

export const ALL_PRODUCT_ERRORS = 'ALL_PRODUCT_CLERA'; 