
export const NEW_REVIEW_REQUEST = 'NEW_REVIEW_REQUEST';
export const NEW_REVIEW_SUCCESS = 'NEW_REVIEW_SUCCESS';
export const NEW_REVIEW_FAIL = 'NEW_REVIEW_FAIL';
export const NEW_REVIEW_RESET = 'NEW_REVIEW_RESET';


export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
export const DELETE_REVIEW_RESET = 'DELETE_REVIEW_RESET';


export const ALL_REVIEW_REQUEST = 'ALL_REVIEW_REQUEST';
export const ALL_REVIEW_SUCCESS = 'ALL_REVIEW_SUCCESS';
export const ALL_REVIEW_FAIL = 'ALL_REVIEW_FAIL';

export const PRODUCT_REVIEW_REQUEST = 'PRODUCT_REVIEW_REQUEST';
export const PRODUCT_REVIEW_SUCCESS = 'PRODUCT_REVIEW_SUCCESS';
export const PRODUCT_REVIEW_FAIL = 'PRODUCT_REVIEW_FAIL';

export const REVIEWS_CLEAR_ERROR = 'REVIEWS_CLEAR_ERROR';
