export const SEO_REQUEST = "SEO_REQUEST";
export const SEO_SUCCESS = "SEO_SUCCESS";
export const SEO_FAIL = "SEO_FAIL";


export const CREATE_SEO_REQUEST = "CREATE_SEO_REQUEST";
export const CREATE_SEO_SUCCESS = "CREATE_SEO_SUCCESS";
export const CREATE_SEO_FAIL = "CREATE_SEO_FAIL";
export const CREATE_SEO_RESET = "CREATE_SEO_RESET";

export const SEO_CLEAR_SEO = "SEO_CLEAR_SEO";
