export const LOGIN_REQUEST = 'LOGIN_REQUEST'; 
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'; 
export const LOGIN_FAIL = 'LOGIN_FAIL'; 

export const SINGUP_REQUEST = 'SINGUP_REQUEST'; 
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS'; 
export const SINGUP_FAIL = 'SINGUP_FAIL'; 

export const OTP_REQUEST = 'OTP_REQUEST'; 
export const OTP_SUCCESS = 'OTP_SUCCESS'; 
export const OTP_FAIL = 'OTP_FAIL'; 

export const OTP_RESENDOTP_REQUEST = 'OTP_RESENDOTP_REQUEST'; 
export const OTP_RESENDOTP_SUCCESS = 'OTP_RESENDOTP_SUCCESS'; 
export const OTP_RESENDOTP_FAIL = 'OTP_RESENDOTP_FAIL'; 

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'; 
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'; 
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'; 

export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'; 
export const LOGOUT_USER_FAIL = 'LOGOUT_USER_FAIL'; 


export const UPDATE_PROFILE_REQUEST = 'UPDATE_FILE_REQUEST'; 
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_FILE_SUCCESS'; 
export const UPDATE_PROFILE_FAIL = 'UPDATE_FILE_FAIL'; 
export const UPDATE_PROFILE_RESET = 'UPDATE_FILE_RESET';   

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST'; 
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS'; 
export const UPDATE_PASSWORD_FAIL = 'UPDATE_PASSWORD_FAIL'; 
export const UPDATE_PASSWORD_RESET = 'UPDATE_PASSWORD_RESET'; 


export const ALL_USER_REQUEST = 'ALL_USER_REQUEST'; 
export const ALL_USER_SUCCESS = 'ALL_USER_SUCCESS'; 
export const ALL_USER_FAIL = 'ALL_USER_FAIL'; 

export const ALL_USER_DETAILS_REQUEST = 'ALL_USER_DETAILS_REQUEST'; 
export const ALL_USER_DETAILS_SUCCESS = 'ALL_USER_DETAILS_SUCCESS'; 
export const ALL_USER_DETAILS_FAIL = 'ALL_USER_DETAILS_FAIL'; 

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST'; 
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS'; 
export const UPDATE_USER_DETAILS_FAIL = 'UPDATE_USER_DETAILS_FAIL'; 
export const UPDATE_USER_DETAILS_RESET = 'UPDATE_USER_DETAILS_RESET'; 


export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'; 
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS'; 
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL'; 
export const DELETE_USER_RESET = 'DELETE_USER_RESET'; 

export const FORGET_PASSWORD_REQUEST = 'FORGET_PASSWORD_REQUEST'; 
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS'; 
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL'; 
export const FORGET_PASSWORD_RESET = 'FORGET_PASSWORD_RESET'; 


export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'; 
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'; 
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'; 
export const RESET_PASSWORD_RESET = 'RESET_PASSWORD_RESET'; 

export const LOGIN_ERRORS = 'LOGIN_CLEAR'; 