export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';

export const CREATE_WISHLIST_SUCCESS="CREATE_WISHLIST_SUCCESS";
export const CREATE_WISHLIST_REQUEST="CREATE_WISHLIST_REQUEST";
export const CREATE_WISHLIST_FAILED="CREATE_WISHLIST_FAILED";
export const CREATE_WISHLIST_RESET="CREATE_WISHLIST_RESET";

export const GET_WISHLIST_SUCCESS="GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_REQUEST="GET_WISHLIST_REQUEST";
export const GET_WISHLIST_FAILED="GET_WISHLIST_FAILED";

export const WISHLIST_CLEAR_ERROR="WISHLIST_CLEAR_ERROR";




export const REMOVE_WISHLIST_ITEM = 'REMOVE_WISHLIST_ITEM'
